server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ecommerce
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # This tells Hibernate to create tables if missing
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Explicitly set the dialect
        format_sql: true
    generate-ddl: true # Additional force flag for table generation

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Outgoing: Label the event as 'orderEvent'
        spring.json.type.mapping: "orderEvent:org.com.order.event.OrderEvent"
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.com.order.event"
        # Incoming: Map 'paymentEvent' nickname to our local PaymentEvent class
        spring.json.type.mapping: "paymentEvent:org.com.order.event.PaymentEvent"

  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG

cart:
  service:
    url: ${CART_SERVICE_URL:http://localhost:8081}